### ISSUE TITLE
Normal MC join text shows before someone joins the actual gamemode

### ISSUE THREAD

**Issue by Nostalgion** [CeedricCom/Earth#6]
something to do with proxy settings?

**Comment by ceeedric** [comment]
What do you mean by "Normal MC join text"? Is that the MOTD from on the minecraft added servers list? Or is this in-game?

**Comment by Nostalgion** [comment]
like, as if someone were joining a vanilla world, but their join message showed up in the gamemode server before they actually joined via server selector

**Comment by ceeedric** [comment]
If you meant the "player left the game" messages I just fixed that by using essentials config. Please be more clear and maybe provide screenshots if that wasn't the issue
